--- #YAML:1.0
name:               Net-SMS-Optimus
version:            0.05
abstract:           Send SMS through www.optimus.pt
author:
    - Ruben Fonseca <root@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:   0.53
    HTML::Form:      1.054
    HTTP::Cookies:   1.39
    LWP::UserAgent:  2.033
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
