# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMS-Optimus
version:      0.02
version_from: lib/Net/SMS/Optimus.pm
installdirs:  site
requires:
    HTML::Form:                    1.054
    HTTP::Cookies:                 1.39
    LWP::UserAgent:                2.033
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
